<?php
// Autogenerated by SpotiDown
if (!defined('SPOTIPY_CLIENT_ID')) define('SPOTIPY_CLIENT_ID', '384aba32562344739865f70ebbe237d0');
if (!defined('SPOTIPY_CLIENT_SECRET')) define('SPOTIPY_CLIENT_SECRET', '8b9ff9dea3d74e6bbbb5e0894a14b6d2');
if (!defined('SPOTIFY_COOKIE')) define('SPOTIFY_COOKIE', 'AQBgNLoknSRje60KLIZYSsCEByyJuIQ--UxmLmGJ5vXnIKYuUdwvbUbD5Py7IKq4dkyb3KOLU1i22KeKcWFkw_RVjgp_1hSY9cYR7StNmqgmtUcZ8_Tp50veftrXXEsl_PE0UErpGZiJbtDQzWduuTeeTtIgmbc450JUdXWcINPpKjN78_GhJuxrbnhbiKgGK0GkeJZzD98ZuC9DUpucf-sw7ojXBygKxsSN7lXRxsGdDl9CkL40uDMF4i5lN8hTUuwmDLr-BRy_rw');
if (!defined('DEFAULT_AUDIO_PROVIDER')) define('DEFAULT_AUDIO_PROVIDER', 'piped');
