<?php
// Autogenerated by SpotiDown
if (!defined('SPOTIPY_CLIENT_ID')) define('SPOTIPY_CLIENT_ID', '384aba32562344739865f70ebbe237d0');
if (!defined('SPOTIPY_CLIENT_SECRET')) define('SPOTIPY_CLIENT_SECRET', '8b9ff9dea3d74e6bbbb5e0894a14b6d2');
if (!defined('DEFAULT_AUDIO_PROVIDER')) define('DEFAULT_AUDIO_PROVIDER', 'piped');
